apiVersion: v1
kind: Namespace
metadata:
    name: my-end-to-end-tests
---
apiVersion: batch/v1
kind: Job
metadata:
    name: e2e-chrome-mysite-1
    namespace: my-end-to-end-tests
spec:
    parallelism: 1
    completions: 1
    backoffLimit: 3
    activeDeadlineSeconds: 20
    template:
        metadata:
            labels:
                app: "e2e-chrome-mysite-1"
                run: "1"
                version: "1"
        spec:
            restartPolicy: Never
            containers:
            - name: chrome
              image: my-repository-name/container-e2e
              env:
              - name: "TARGET_URL"
                value: "http://www.mywebsite.com"
              - name: "BROWSER"
                value: "chrome"
              - name: "SELENIUM_HOST"
                value: "127.0.0.1"
              - name: "SELENIUM_PORT"
                value: "4444"
